# Generated by Django 5.1.6 on 2025-03-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='loca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='whatsapp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
