# Generated by Django 5.1.6 on 2025-05-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_details_email_details_loca_details_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='loca',
            new_name='location',
        ),
    ]
